"""
Full sample dataset for download: realistic healthcare papers CSV format.
"""
import pandas as pd

FULL_SAMPLE_ROWS = [
    {
        "pmid": "38123456",
        "title": "Machine learning in healthcare improves diagnosis and treatment outcomes: a systematic review",
        "abstract": "Background: Machine learning (ML) applications in healthcare have expanded rapidly. We conducted a systematic review to evaluate the impact of ML on diagnostic accuracy and treatment outcomes. Methods: We searched PubMed, Embase, and Cochrane from 2018 to 2024. Results: Of 2,450 studies screened, 89 met inclusion criteria. ML models showed median sensitivity of 0.92 and specificity of 0.88 for diagnostic tasks. Conclusion: ML can support clinical decision-making when integrated with clinician oversight.",
        "authors": "Smith J; Johnson A; Williams B",
        "journal": "Nature Medicine",
        "year": 2024,
        "keywords": "machine learning; healthcare; systematic review; diagnosis",
    },
    {
        "pmid": "38098765",
        "title": "Deep learning models for medical image analysis: performance and interpretability",
        "abstract": "Deep learning has achieved high accuracy in radiology and pathology. This paper compares CNN and transformer-based models on chest X-ray and histology datasets. We discuss trade-offs between accuracy and interpretability and recommend practices for clinical deployment.",
        "authors": "Chen L; Patel R; Kumar S",
        "journal": "Radiology: Artificial Intelligence",
        "year": 2024,
        "keywords": "deep learning; medical imaging; radiology; interpretability",
    },
    {
        "pmid": "37987654",
        "title": "Natural language processing for extraction of clinical information from electronic health records",
        "abstract": "NLP techniques enable structured extraction from free-text clinical notes. We present a pipeline for named entity recognition and relation extraction applied to discharge summaries. F1 scores exceeded 0.85 for key entities. Integration with EHR systems is discussed.",
        "authors": "Davis M; Wilson K; Brown T",
        "journal": "Journal of Biomedical Informatics",
        "year": 2023,
        "keywords": "NLP; electronic health records; clinical notes; NER",
    },
    {
        "pmid": "37876543",
        "title": "AI literacy among clinicians and patients: a survey and recommendations",
        "abstract": "Understanding and trust in AI systems vary among healthcare providers and patients. We surveyed 500 clinicians and 1,200 patients. Results indicate gaps in AI literacy and a need for targeted education. We recommend curriculum and communication guidelines.",
        "authors": "Garcia E; Martinez L; Lee H",
        "journal": "JMIR Medical Education",
        "year": 2023,
        "keywords": "AI literacy; patient perception; clinician education; trust",
    },
    {
        "pmid": "37765432",
        "title": "Ethical considerations in artificial intelligence for healthcare delivery",
        "abstract": "AI in healthcare raises ethical questions about fairness, accountability, and transparency. We review frameworks and propose a checklist for developers and institutions. Case studies illustrate bias and mitigation strategies.",
        "authors": "Anderson P; Thomas N; White S",
        "journal": "Bioethics",
        "year": 2023,
        "keywords": "ethics; AI; healthcare; fairness; bias",
    },
    {
        "pmid": "37654321",
        "title": "Predictive analytics for clinical decision support: a meta-analysis",
        "abstract": "Predictive models for readmission, deterioration, and treatment response have been widely studied. We meta-analyzed 120 studies. AUC ranged from 0.72 to 0.91. Heterogeneity was high; we discuss sources and implications for implementation.",
        "authors": "Taylor R; Clark J; Lewis M",
        "journal": "Journal of the American Medical Informatics Association",
        "year": 2023,
        "keywords": "predictive analytics; clinical decision support; meta-analysis",
    },
    {
        "pmid": "37543210",
        "title": "Electronic health records and machine learning for risk stratification",
        "abstract": "EHR data combined with ML can identify patients at risk for adverse events. We developed and validated a risk stratification model using structured and unstructured EHR data from 50,000 patients. The model improved early intervention rates.",
        "authors": "Harris D; Martin F; Young W",
        "journal": "Lancet Digital Health",
        "year": 2023,
        "keywords": "EHR; machine learning; risk stratification",
    },
    {
        "pmid": "37432109",
        "title": "Patient perception of AI in medicine: a qualitative study",
        "abstract": "We conducted focus groups with patients to explore attitudes toward AI-assisted diagnosis and treatment. Themes included trust in clinicians, desire for transparency, and concerns about data privacy. Recommendations for patient communication are provided.",
        "authors": "Moore S; Jackson C; Adams R",
        "journal": "Patient Education and Counseling",
        "year": 2023,
        "keywords": "patient perception; trust; qualitative; AI",
    },
    {
        "pmid": "37321098",
        "title": "Barriers to clinical adoption of artificial intelligence tools",
        "abstract": "Despite promising performance, AI tools are not widely adopted in practice. We interviewed 30 clinical leaders and identified barriers: workflow integration, regulation, evidence standards, and reimbursement. We suggest policy and design recommendations.",
        "authors": "Walker I; Hall G; King P",
        "journal": "BMJ Health & Care Informatics",
        "year": 2022,
        "keywords": "adoption; barriers; implementation; policy",
    },
    {
        "pmid": "37210987",
        "title": "Systematic review of AI applications in radiology and pathology",
        "abstract": "We systematically reviewed AI applications in imaging. Included studies covered detection, segmentation, and grading. Performance was comparable to experts in many tasks. Limitations include dataset bias and generalizability. We recommend reporting standards.",
        "authors": "Scott B; Green D; Hill F",
        "journal": "European Radiology",
        "year": 2022,
        "keywords": "radiology; pathology; systematic review; AI",
    },
    {
        "pmid": "37109876",
        "title": "Federated learning for healthcare: privacy-preserving collaborative models",
        "abstract": "Federated learning allows training on distributed data without centralizing records. We review healthcare applications and present a multi-site experiment for mortality prediction. We discuss challenges in fairness and communication cost.",
        "authors": "Evans V; Turner U; Phillips Q",
        "journal": "NPJ Digital Medicine",
        "year": 2022,
        "keywords": "federated learning; privacy; healthcare; collaboration",
    },
    {
        "pmid": "37008765",
        "title": "Large language models for clinical documentation: opportunities and risks",
        "abstract": "LLMs can assist in drafting clinical notes and summaries. We evaluate GPT-based models on de-identification and summarization tasks. We discuss risks of hallucination and recommend human-in-the-loop workflows and monitoring.",
        "authors": "Roberts C; Bennett A; Wright I",
        "journal": "Journal of the American Medical Association",
        "year": 2024,
        "keywords": "large language models; clinical documentation; GPT; safety",
    },
    {
        "pmid": "36907654",
        "title": "AI-driven drug discovery: recent advances and open challenges",
        "abstract": "AI is increasingly used in drug discovery for target identification, virtual screening, and de novo design. We survey recent literature and highlight successes and open challenges in validation and translation.",
        "authors": "Mitchell O; Hughes J; Collins E",
        "journal": "Drug Discovery Today",
        "year": 2023,
        "keywords": "drug discovery; AI; virtual screening; pharma",
    },
    {
        "pmid": "36806543",
        "title": "Wearable devices and AI for continuous health monitoring",
        "abstract": "Wearables generate high-frequency physiological data. We review AI methods for arrhythmia detection, fall detection, and chronic disease management. We discuss regulatory and usability considerations for clinical use.",
        "authors": "Parker S; Cooper T; Morgan D",
        "journal": "Digital Health",
        "year": 2023,
        "keywords": "wearables; continuous monitoring; AI; digital health",
    },
    {
        "pmid": "36705432",
        "title": "Explainable AI in healthcare: methods and evaluation",
        "abstract": "Explainability is critical for clinician trust and regulatory compliance. We compare saliency maps, attention, and natural language explanations. We propose an evaluation framework and report results on ICU prediction and imaging tasks.",
        "authors": "Stewart L; Campbell R; Murphy F",
        "journal": "Artificial Intelligence in Medicine",
        "year": 2023,
        "keywords": "explainability; XAI; healthcare; evaluation",
    },
    {
        "pmid": "36604321",
        "title": "Bias and fairness in clinical AI: detection and mitigation",
        "abstract": "Clinical AI can perpetuate or amplify disparities. We review sources of bias and present methods for detection and mitigation. We evaluate several models on fairness metrics across demographic groups and recommend practices.",
        "authors": "Reed G; Brooks N; Hayes J",
        "journal": "Health Affairs",
        "year": 2022,
        "keywords": "bias; fairness; health equity; AI",
    },
    {
        "pmid": "36503210",
        "title": "Robotics and AI in surgery: current state and future directions",
        "abstract": "Surgical robots and AI assistance are evolving rapidly. We review systems for planning, navigation, and execution. We discuss evidence on outcomes and training requirements. Regulatory and cost considerations are summarized.",
        "authors": "Baker H; Fisher A; Gray K",
        "journal": "Annals of Surgery",
        "year": 2022,
        "keywords": "surgery; robotics; AI; navigation",
    },
    {
        "pmid": "36402109",
        "title": "Mental health applications of AI: screening, support, and therapy",
        "abstract": "AI is used for screening depression and anxiety, chatbots for support, and personalized interventions. We review effectiveness and ethical issues including crisis detection and therapeutic relationship. We recommend guidelines for deployment.",
        "authors": "Ward L; Russell S; Butler T",
        "journal": "Lancet Psychiatry",
        "year": 2022,
        "keywords": "mental health; chatbots; screening; ethics",
    },
    {
        "pmid": "36301098",
        "title": "Regulatory landscape for AI in medical devices: US and EU comparison",
        "abstract": "We compare FDA and EU MDR approaches to AI-based medical devices. We discuss software as a medical device, clinical evidence requirements, and post-market monitoring. We highlight gaps and ongoing policy developments.",
        "authors": "Howard E; Sanders R; Price M",
        "journal": "Regulatory Affairs",
        "year": 2022,
        "keywords": "regulation; FDA; EU MDR; medical devices",
    },
    {
        "pmid": "36200987",
        "title": "AI for pandemic preparedness and response",
        "abstract": "During COVID-19, AI was used for forecasting, drug repurposing, and vaccine design. We review applications and lessons learned. We recommend infrastructure and governance for future pandemic response.",
        "authors": "Cox N; James V; Watson L",
        "journal": "Science",
        "year": 2022,
        "keywords": "pandemic; COVID-19; forecasting; vaccine",
    },
    {
        "pmid": "36100876",
        "title": "Telehealth and AI: integration for rural and underserved populations",
        "abstract": "Telehealth expanded during the pandemic. AI can support triage, interpretation, and follow-up. We present a framework for integrating AI into telehealth workflows and report a pilot in rural clinics.",
        "authors": "Foster D; Richardson A; Simmons G",
        "journal": "Journal of Rural Health",
        "year": 2022,
        "keywords": "telehealth; rural health; AI; access",
    },
    {
        "pmid": "36000765",
        "title": "Clinical decision support systems: effectiveness and implementation",
        "abstract": "CDSS can improve adherence to guidelines and reduce errors. We meta-analyze implementation studies and identify success factors: workflow integration, clinician involvement, and continuous evaluation. We provide an implementation checklist.",
        "authors": "Bryant H; Nelson I; Carter O",
        "journal": "Implementation Science",
        "year": 2021,
        "keywords": "clinical decision support; implementation; effectiveness",
    },
    {
        "pmid": "35900654",
        "title": "Precision medicine and AI: matching treatments to patients",
        "abstract": "AI can identify patient subgroups and predict treatment response. We review applications in oncology, cardiology, and psychiatry. We discuss integration with genomics and real-world data. Challenges in evidence generation are addressed.",
        "authors": "Sanders P; Hayes R; Turner W",
        "journal": "Cell",
        "year": 2021,
        "keywords": "precision medicine; treatment selection; AI; subgroups",
    },
    {
        "pmid": "35800543",
        "title": "Data quality and curation for healthcare AI",
        "abstract": "Model performance depends on data quality. We discuss common issues: missing values, label noise, and dataset shift. We present curation pipelines and quality metrics used in our institution and recommend best practices.",
        "authors": "Morgan E; Bell J; Wright S",
        "journal": "JAMIA Open",
        "year": 2021,
        "keywords": "data quality; curation; healthcare data; ML",
    },
    {
        "pmid": "35700432",
        "title": "Human-AI collaboration in diagnostic workflows",
        "abstract": "Optimal workflows often combine AI suggestions with human judgment. We review studies on human-AI teaming in radiology and pathology. We present design principles for interfaces and feedback that improve combined performance.",
        "authors": "Cole R; Howard M; Stewart P",
        "journal": "Human Factors",
        "year": 2021,
        "keywords": "human-AI collaboration; diagnosis; workflow; design",
    },
    {
        "pmid": "35600321",
        "title": "Cost-effectiveness of AI in healthcare: a systematic review",
        "abstract": "We systematically reviewed economic evaluations of AI in healthcare. Few studies met quality criteria. Where reported, results varied by setting and comparator. We recommend standards for future cost-effectiveness studies of AI.",
        "authors": "James K; Wood L; Hill M",
        "journal": "Value in Health",
        "year": 2021,
        "keywords": "cost-effectiveness; health economics; AI; systematic review",
    },
]


def get_full_sample_df() -> pd.DataFrame:
    """Return a full sample DataFrame for download (CSV format)."""
    return pd.DataFrame(FULL_SAMPLE_ROWS)
